name: Publish to crates.io

on:
  push:
    tags:
      - "v[0-9]+.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CRATES_IO_API_TOKEN }}
