name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
